#Type  Path                               Mode  User  Group     Age  Argument
f      /etc/authelia/configuration.yml    0640  root  authelia  -    -
Z      /etc/authelia/configuration.*.yml  0640  root  authelia  -    -
Z      /etc/authelia/configuration.yml.*  0640  root  authelia  -    -
